name: aoc
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - numpy
  - pandas
  - ipykernel
  - matplotlib
  # used by VS Code:
  - pylint
  - rope # renaming
  - pep8
  - autopep8 # formatting